<main>
    <p>
        This is a tool for exploring seeds of seeded runs in Zoominoes.
    </p>
    <p>
        As background, it is useful to know a little about how the RNG in Zoominoes works.
        For each seeded run, the game has a number of independent streams of randomness that it uses.
        The seed fully determines all the values generated by these streams of randomness.
        The streams that are relevant for gameplay are:
    </p>
    <ul>
        <li><b>General</b> - This is used for special events, random starters, shuffling the deck, and a few other minor things.</li>
        <li><b>Rewards</b> - This is used for the animal, snack, and other rewards given at the end of a day.</li>
        <li><b>Shop</b> - This is used for all snacks, gems, and souvenirs on the initial shop screens.</li>
        <li><b>ShopRoll</b> - This is used for all snacks, gems, and souvenirs on rerolled shop screens.</li>
        <li><b>Create</b> - This is used for all random items given by animals and souvenirs as well as all the random transformations from animal and soda effects.
            It is also used to determine the color of reward animals.</li>
    </ul>
    <p>
        For most items, the game first picks a rarity and then picks a random item from all items of that rarity.
        The distribution of rarities depends on the day, with higher rarities becoming more likely during later days.
        It is worth noting that some rarities are completely impossible to get during certain parts of the game.
        For example, mythical animals have a chance of 0% before day 5, and common animals have a chance of 0% after day 6.
    </p>
    <p>
        As a result of how the RNG in the game works, there are some limitations to the ability to predict seeded runs.
        While the seed fully determines the random values generated, the game may interpret the values differently depending on your actions during the run.
        The following is a (non-exhaustive) list of caveats to keep in mind when using this tool to view or search for specific seeds:
    </p>
    <ul>
        <li>You can't get the same souvenir twice. As a result, getting any souvenir affects all souvenirs offered in subsequent shops.
            This tool assumes that you have no souvenirs when calculating souvenirs offered in the shop, which unfortunately means that its predictions become incorrect as soon as you buy a souvenir.</li>
        <li>The same issue affects souvenir rewards given by Trinket. Any souvenir you choose affects all subsequent souvenir rewards,
            so predicting any rewards beyond the first one is impossible without user input. Because of this, this tool does not show predicted souvenir rewards for Trinket.</li>
        <li>Anything that changes the number of snacks, gems, souvenirs, or sales in the shop changes the offered items in all subsequent shops.
            This includes for example Coupon Clippers and Delivery Stork.</li>
        <li>Locking the shop changes the offered items in all subsequent shops, but only if the locked items include at least one that is on sale.</li>
        <li>Anything that forces a specific type of animal to appear in the rewards changes all subsequent animal rewards.
            This includes for example the Land, Sea, and Sky Incense.</li>
    </ul>
</main>

<style>
    main {
        max-width: 800px;
        margin: 0 auto;
        font-size: 1.2rem;
    }

    b {
        font-weight: 600;
    }
</style>