<main>
    <p>
        This is a tool for exploring seeds of seeded runs in Zoominoes.
    </p>
    <p>
        As background, it is useful to know a little about how the RNG in Zoominoes works.
        For each seeded run, the game has a number of independent streams of randomness that it uses.
        The seed fully determines all the values generated by these streams of randomness.
        The streams that are relevant for gameplay are:
    </p>
    <ul>
        <li><b>General</b> - This is used for special events, random starters, shuffling the deck, and a few other minor things.</li>
        <li><b>Rewards</b> - This is used for the animal, snack, and other rewards given at the end of a day.</li>
        <li><b>Shop</b> - This is used for all snacks, gems, and souvenirs on the initial shop screens.</li>
        <li><b>ShopRoll</b> - This is used for all snacks, gems, and souvenirs on rerolled shop screens.</li>
        <li><b>Create</b> - This is used for all random items given by animals and souvenirs as well as all the random transformations from animal and soda effects.
            It is also used to determine the color of reward animals.</li>
    </ul>
    <p>
        As a result of how the RNG in the game works, there are some limitations to the ability to predict seeded runs.
        While the seed fully determines the random values generated, the game may interpret the values differently depending on your actions during the run.
        The following is a (non-exhaustive) list of caveats to keep in mind when using this tool to view or search for specific seeds:
    </p>
    <ul>
        <li>You can't get the same souvenir twice. As a result, getting any souvenir affects all the souvenirs offered in subsequent shops.
            This tool assumes that you have no souvenirs when calculating souvenirs offered in the shop, which unfortunately means that its predictions become incorrect as soon as you buy a souvenir.</li>
        <li>Anything that changes the number of snacks, gems, souvenirs, or sales in the shop changes the offered items in all subsequent shops.
            This includes for example Coupon Clippers and Delivery Stork.</li>
    </ul>
</main>

<style>
    main {
        max-width: 800px;
        margin: 0 auto;
        font-size: 1.2rem;
    }
</style>